//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Commate.rc
//
#define IDC_CLEAR                       4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define CG_IDR_POPUP_RECV_LIST_VIEW     105
#define CG_IDR_POPUP_C232PROGRAM_VIEW   106
#define IDR_MAINFRAME                   128
#define IDR_ProbeTYPE                   129
#define IDB_BITMAP_LED                  130
#define IDD_PORT_SETTING                131
#define IDD_PORT_RECEIVED               132
#define IDD_CALCULATE                   133
#define IDR_TOOLBAR_INPUT               134
#define IDB_BITMAP_STEPS                135
#define IDB_BITMAP_SEND_RECV            136
#define IDD_CONVERTION_DLG              138
#define IDD_TITLE_BAR                   139
#define IDD_SEND_RECYCYLE               140
#define IDD_RECV_BUFF                   141
#define IDR_MENU_RECV_BUFF              142
#define IDD_DISPLAY                     143
#define IDD_IP_FILTER                   144
#define IDD_DIALOG_ETH_SELECT           310
#define IDC_COMBO_ETH_IFS               1000
#define IDC_CURRENT_PORT                1001
#define IDC_BOUD_RATE                   1002
#define IDC_BYTE_SIZE                   1003
#define IDC_EDIT_INPUT_BUFFER           1003
#define IDC_EDIT_CALCULATE_FORMULA      1006
#define IDC_EDIT_CALCULATE_RESULT       1007
#define IDC_BUTTON_EXECUTE              1008
#define IDC_RADIO_SERIAL                1009
#define IDC_RADIO_TCPIP                 1010
#define IDC_SETTING_IPADDRESS           1011
#define IDC_EDIT_TCPIP_PORT             1012
#define IDC_EDIT_CONVERTION             1013
#define IDC_RADIO_UDPIP                 1013
#define IDC_EDIT_LOCAL_PORT             1014
#define IDC_EDIT_IP_PORT1               1015
#define IDC_EDIT_LOCAL_PORT3            1016
#define IDC_EDIT_IP_PORT2               1016
#define IDC_RICHEDIT_RECEIVED           1017
#define IDC_RADIO_HEX                   1018
#define IDC_RADIO_ASCII                 1019
#define IDC_EDIT_CYCLE_TIMER            1020
#define IDC_LIST_RECV_DATA              1022
#define IDC_EDIT_RECV_DATA              1023
#define IDC_CHECK_IP_TRANSFER           1024
#define IDC_IPADDRESS_TERM1             1025
#define IDC_IPADDRESS_TERM2             1026
#define IDC_LIST_RUNTIME_VIEW           1027
#define IDC_LIST_SIGNAL_VIEW            1028
#define IDC_EDIT_SHOWDATA_VIEW          1029
#define IDC_IPADDRESS1                  1029
#define IDC_FILTER_IP                   1029
#define IDC_IP_INSERT                   1030
#define IDC_IP_DELETE                   1031
#define IDC_IP_MODIFY                   1032
#define IDC_LIST_IP_FILTERS             1033
#define IDC_FILTER_INSERT               1034
#define IDC_FILTER_DELETE               1035
#define IDC_FILTER_MODIFY               1036
#define IDC_LIST1                       1037
#define IDC_LIST_FILTER                 1037
#define IDC_CHECK_                      1038
#define IDC_CHECK_SIMPLIFY_MODE         1038
#define IDC_EDIT1                       1040
#define IDC_EDIT_IF_DETAILS             1040
#define IDC_STOP1                       4015
#define IDC_STOP2                       4016
#define IDC_PARITY_NO                   4017
#define IDC_PARITYODD                   4018
#define IDC_PARITYEVEN                  4019
#define IDC_STOP15                      4022
#define ID_SEND_VIEW_HEX                32774
#define ID_SEND_VIEW_ASCII              32775
#define ID_SEND_VIEW_CANCEL             32777
#define ID_RECV_LIST_VIEW_CLEAR         32779
#define ID_RECV_LIST_VIEW_SAVELOG       32783
#define ID_SEND_VIEW_CYCLESEND          32784
#define ID_RECV_LIST_VIEW_HEX           32785
#define ID_SEND_VIEW_CHECKSUM           32786
#define ID_SEND_VIEW_CHECKSUM2          32787
#define ID_SEND_VIEW_CHECKCRC           32788
#define ID_SEND_VIEW_TRANS_ASCII        32789
#define ID_SEND_VIEW_TRANS_HEX          32790
#define ID_SEND_VIEW_CALCULATER         32791
#define ID_SEND_VIEW_ASCII_LINE         32792
#define ID_POPUP_EXEC_CLEAR             32793
#define ID_POPUP_EXEC_EXECUTE           32794
#define ID_RECV_BUFF_DELETE             32795
#define ID_POPUP_EXEC_STOP              32796
#define ID_RECV_LIST_VIEW_REVIEW        32797
#define ID_RECV_BUFF_REFRESH            32798
#define ID_POPUP_EXEC_SEL_ALL           32799
#define ID_SENDVIEW_SEL_ALL             32800
#define ID_RECV_BUFF_ASCII_HEX          32801
#define ID_SENDVIEW_CLEAR               32802
#define ID_RECV_LIST_VIEW_OPENLOG       32803
#define ID_RECV_BUFF_FILTER_RECV        32804
#define ID_RECV_BUFF_FILTER_SEND        32805
#define ID_RECV_BUFF_FILTER_ALL         32806
#define ID_SEND_VIEW_TXT_LF             32807
#define ID_SEND_VIEW_ECHO               32808
#define ID_POPUP_EXEC_LOAD              32809
#define ID_VIEW_RUNTIME                 32810
#define ID_VIEW_SIGNAL                  32811
#define ID_VIEW_COLOUR                  32812
#define ID_SEND_VIEW_EDIT               32813
#define ID_RECV_LIST_VIEW_COLOR         32814
#define ID_RECV_LIST_VIEW_SELECT_ALL    32815
#define ID_RECV_LIST_VIEW_COPY          32816
#define ID_VIEW_REFRESH                 32818
#define ID_VIEW_SHOWDATA                32819
#define ID_RECV_LIST_VIEW_FILTER        32820
#define ID_POPUP_EXEC_DEBUG             32821
#define ID_POPUP_EXEC_CLEAR_TRACE       32822

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32823
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
